### ISSUE TITLE
Question 14 has a vague answer.

### ISSUE THREAD

**Issue by tkore** [lydiahallie/javascript-questions#26]
> All objects have prototypes, except for the **base object**

It may be worth noting that by 'base object', you mean an object created by the user or an object that is created using the `new` keyword.

**Comment by ThomasR** [comment]
What about `Object.create(null)`?

**Comment by A1rPun** [comment]
This closed issue is related #10

**Comment by lydiahallie** [comment]
Thanks for your input! This issue is not related to #10, it has been fixed now!

**Comment by rosschapman** [comment]
I still don't see anything about `Object.create(null)` in the answer explanation? 

Also, this line 

>The base object is the object created by the user, or an object that is created using the new keyword.

does not seem correct. When you are talking about the "base object" I would assume you mean the root object as in `Object.prototype`. (Like, if I kept calling the static method `Object.getPrototypeOf` on something and what it returns, and then again, etc.... I'd eventually reach this "base object.") If that is so, then an "object created by a user" or using the `new` operator would most likely delegate to `Object.prototype` unless done with `Object.create(null)`. Or am I interpreting this answer wrong?

I'm chiming in because this was confusing for a colleague with whom I was working with on this problem yesterday. Thanks!
